version: 2

jobs:
  build:
    docker:
      - image: circleci/node
        user: root

    steps:
      - run:
          name: "Get Hugo"
          command: |
            add-apt-repository ppa:gophers/archive
            apt update
            apt-get install golang-1.9-go
            go get -v github.com/spf13/hugo

      - checkout

      - run:
          name: "Get Submodules"
          command: |
            git submodule sync --recursive
            git submodule update --init --recursive

      - run:
          name: "Build Site"
          command: hugo

      - run:
          name: "Push to firebase"
          command: |
            npm install --save-dev firebase-tools
