version: 2

jobs:
  build:
    docker:
      - image: circleci/golang
        user: root

    steps:
      - run:
          name: "Get Hugo"
          command: go get -v github.com/spf13/hugo

      - checkout

      - run:
          name: "Get Submodules"
          command: |
            git submodule sync --recursive
            git submodule update --init --recursive

      - run:
          name: "Build Site"
          command: hugo

      - run:
          name: "Push to firebase"
          command: |
            curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -
            apt-get install -y nodejs
            npm install -g firebase
