version: 2

defaults: &defaults
  working_directory: ~/hugo
#  environment:
#    HUGO_BUILD_DIR: "~/hugo/public"

jobs:
  build:
    <<: *defaults

    docker:
      - image: cibuilds/hugo:latest

    steps:
      - checkout

      - run:
          name: "Get Submodules"
          command: |
            git submodule sync --recursive
            git submodule update --init --recursive

      - run:
          name: "Build Site"
          command: |
            HUGO_ENV=production hugo -v

      - persist_to_workspace:
          root: ~/hugo
          paths:
            - ./public

  deploy:
    <<: *defaults

    docker:
      - image: circleci/node:10.13.0

    steps:
      - checkout

      - attach_workspace:
          at: ~/hugo

      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      - run:
          name: "Install packages"
          command: |
            npm install

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      - deploy:
          name: "Deploy"
          command: |
            npm run deploy

workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy:
          requires:
            - build
