version: 2

jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/hugo
    environment:
      HUGO_BUILD_DIR: ~/hugo/public

    steps:
      - checkout

      - run:
          name: "Get Submodules"
          command: |
            git submodule sync --recursive
            git submodule update --init --recursive

      - run:
          name: "Build Site"
          command: |
            HUGO_ENV=production hugo -v -d public

      - persist_to_workspace:
          root: .
          paths:
            - public/*

  deploy:
    docker:
      - image: circleci/node:10.13.0

    steps:
      - checkout

      - attach_workspace:
          at: public

      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      - run:
          name: "Check root"
          command: |
            ls
      
      - run:
          name: "Check public"
          command: |
            ls public

      - run:
          name: "Install packages"
          command: |
            npm install

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      - deploy:
          name: "Deploy"
          command: |
            npm run deploy

workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy:
          requires:
            - build
